// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package config_queries

import (
	"context"
)

const createConfig = `-- name: CreateConfig :one
INSERT INTO matreshka.configs
    (name, type)
VALUES ($1, $2)
RETURNING id
`

type CreateConfigParams struct {
	Name string
	Type MatreshkaConfigType
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createConfig, arg.Name, arg.Type)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteByName = `-- name: DeleteByName :exec
WITH config_id AS (SELECT id
                   FROM matreshka.configs
                   WHERE matreshka.configs.name = $1),
     _delete_values AS (
         DELETE FROM matreshka.configs_content
             WHERE config_id = config_id.id
             RETURNING true)
DELETE
FROM matreshka.configs
WHERE id = config_id.id
`

func (q *Queries) DeleteByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteByName, name)
	return err
}

const getConfig = `-- name: GetConfig :one
SELECT id,
       name,
       type,
       created_at,
       updated_at
FROM matreshka.configs
WHERE name = $1
FETCH FIRST 1 ROW ONLY
`

func (q *Queries) GetConfig(ctx context.Context, name string) (MatreshkaConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfig, name)
	var i MatreshkaConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
