// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package config_queries

import (
	"context"
)

type Querier interface {
	CreateConfig(ctx context.Context, arg CreateConfigParams) (int32, error)
	DeleteByName(ctx context.Context, name string) error
	GetConfig(ctx context.Context, name string) (MatreshkaConfig, error)
}

var _ Querier = (*Queries)(nil)
