// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package config_queries

import (
	"context"
)

const clearValues = `-- name: ClearValues :exec
DELETE
FROM configs_values
WHERE config_id = (SELECT id FROM configs WHERE name = ?)
  AND version LIKE ?
`

type ClearValuesParams struct {
	Name    string
	Version string
}

func (q *Queries) ClearValues(ctx context.Context, arg ClearValuesParams) error {
	_, err := q.db.ExecContext(ctx, clearValues, arg.Name, arg.Version)
	return err
}

const createConfig = `-- name: CreateConfig :one
INSERT INTO configs
    (name)
VALUES (?)
ON CONFLICT
    DO UPDATE SET name = excluded.name
RETURNING id
`

func (q *Queries) CreateConfig(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createConfig, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConfig = `-- name: GetConfig :one
SELECT id,
       name,
       updated_at
FROM configs
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetConfig(ctx context.Context, name string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig, name)
	var i Config
	err := row.Scan(&i.ID, &i.Name, &i.UpdatedAt)
	return i, err
}
