// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package config_queries

import (
	"database/sql"
	"time"
)

type BinaryConfig struct {
	ConfigID sql.NullInt64
	Data     []byte
	Version  string
}

type Config struct {
	ID        int64
	Name      string
	TypeName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConfigsValue struct {
	ConfigID sql.NullInt64
	Key      string
	Value    string
	Version  string
}
