// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package config_queries

import (
	"context"
)

type Querier interface {
	ClearValues(ctx context.Context, arg ClearValuesParams) error
	CreateConfig(ctx context.Context, name string) (int64, error)
	GetConfig(ctx context.Context, name string) (Config, error)
}

var _ Querier = (*Queries)(nil)
