// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	"go.redsock.ru/rerrors"
	"go.vervstack.ru/matreshka/internal/clients/sqldb"
)

func (a *App) InitDataSources() (err error) {
	a.Sqlite, err = sqldb.New(a.Cfg.DataSources.Sqlite)
	if err != nil {
		return rerrors.Wrap(err, "error during sql connection initialization")
	}

	return nil
}
