// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	"go.redsock.ru/rerrors"
	"go.vervstack.ru/matreshka/internal/transport"
	"net"
)

func (a *App) InitServers() (err error) {
	listenerMASTER, err := net.Listen("tcp", ":"+a.Cfg.Servers.MASTER.Port)
	if err != nil {
		return rerrors.Wrap(err, "error opening listener")
	}
	a.ServerMaster, err = transport.NewServerManager(a.Ctx, listenerMASTER)
	if err != nil {
		return rerrors.Wrap(err, "error during \"MASTER\" server initialization, with name: MASTER")
	}

	return nil
}
