// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: matreshka_api.proto

package matreshka_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatreshkaApi_Version_FullMethodName            = "/matreshka_api.MatreshkaApi/Version"
	MatreshkaApi_ListConfigs_FullMethodName        = "/matreshka_api.MatreshkaApi/ListConfigs"
	MatreshkaApi_CreateConfig_FullMethodName       = "/matreshka_api.MatreshkaApi/CreateConfig"
	MatreshkaApi_SaveConfig_FullMethodName         = "/matreshka_api.MatreshkaApi/SaveConfig"
	MatreshkaApi_GetConfig_FullMethodName          = "/matreshka_api.MatreshkaApi/GetConfig"
	MatreshkaApi_GetConfigNodes_FullMethodName     = "/matreshka_api.MatreshkaApi/GetConfigNodes"
	MatreshkaApi_PatchConfig_FullMethodName        = "/matreshka_api.MatreshkaApi/PatchConfig"
	MatreshkaApi_RenameConfig_FullMethodName       = "/matreshka_api.MatreshkaApi/RenameConfig"
	MatreshkaApi_DeleteConfig_FullMethodName       = "/matreshka_api.MatreshkaApi/DeleteConfig"
	MatreshkaApi_SubscribeOnChanges_FullMethodName = "/matreshka_api.MatreshkaApi/SubscribeOnChanges"
)

// MatreshkaApiClient is the client API for MatreshkaApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatreshkaApiClient interface {
	Version(ctx context.Context, in *Version_Request, opts ...grpc.CallOption) (*Version_Response, error)
	ListConfigs(ctx context.Context, in *ListConfigs_Request, opts ...grpc.CallOption) (*ListConfigs_Response, error)
	CreateConfig(ctx context.Context, in *CreateConfig_Request, opts ...grpc.CallOption) (*CreateConfig_Response, error)
	SaveConfig(ctx context.Context, in *SaveConfig_Request, opts ...grpc.CallOption) (*SaveConfig_Response, error)
	GetConfig(ctx context.Context, in *GetConfig_Request, opts ...grpc.CallOption) (*GetConfig_Response, error)
	GetConfigNodes(ctx context.Context, in *GetConfigNode_Request, opts ...grpc.CallOption) (*GetConfigNode_Response, error)
	PatchConfig(ctx context.Context, in *PatchConfig_Request, opts ...grpc.CallOption) (*PatchConfig_Response, error)
	RenameConfig(ctx context.Context, in *RenameConfig_Request, opts ...grpc.CallOption) (*RenameConfig_Response, error)
	DeleteConfig(ctx context.Context, in *DeleteConfig_Request, opts ...grpc.CallOption) (*DeleteConfig_Response, error)
	SubscribeOnChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeOnChanges_Request, SubscribeOnChanges_Response], error)
}

type matreshkaApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMatreshkaApiClient(cc grpc.ClientConnInterface) MatreshkaApiClient {
	return &matreshkaApiClient{cc}
}

func (c *matreshkaApiClient) Version(ctx context.Context, in *Version_Request, opts ...grpc.CallOption) (*Version_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Version_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) ListConfigs(ctx context.Context, in *ListConfigs_Request, opts ...grpc.CallOption) (*ListConfigs_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigs_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_ListConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) CreateConfig(ctx context.Context, in *CreateConfig_Request, opts ...grpc.CallOption) (*CreateConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConfig_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_CreateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) SaveConfig(ctx context.Context, in *SaveConfig_Request, opts ...grpc.CallOption) (*SaveConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfig_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) GetConfig(ctx context.Context, in *GetConfig_Request, opts ...grpc.CallOption) (*GetConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfig_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) GetConfigNodes(ctx context.Context, in *GetConfigNode_Request, opts ...grpc.CallOption) (*GetConfigNode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigNode_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_GetConfigNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) PatchConfig(ctx context.Context, in *PatchConfig_Request, opts ...grpc.CallOption) (*PatchConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchConfig_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_PatchConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) RenameConfig(ctx context.Context, in *RenameConfig_Request, opts ...grpc.CallOption) (*RenameConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameConfig_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_RenameConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) DeleteConfig(ctx context.Context, in *DeleteConfig_Request, opts ...grpc.CallOption) (*DeleteConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfig_Response)
	err := c.cc.Invoke(ctx, MatreshkaApi_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matreshkaApiClient) SubscribeOnChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeOnChanges_Request, SubscribeOnChanges_Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatreshkaApi_ServiceDesc.Streams[0], MatreshkaApi_SubscribeOnChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeOnChanges_Request, SubscribeOnChanges_Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatreshkaApi_SubscribeOnChangesClient = grpc.BidiStreamingClient[SubscribeOnChanges_Request, SubscribeOnChanges_Response]

// MatreshkaApiServer is the server API for MatreshkaApi service.
// All implementations must embed UnimplementedMatreshkaApiServer
// for forward compatibility.
type MatreshkaApiServer interface {
	Version(context.Context, *Version_Request) (*Version_Response, error)
	ListConfigs(context.Context, *ListConfigs_Request) (*ListConfigs_Response, error)
	CreateConfig(context.Context, *CreateConfig_Request) (*CreateConfig_Response, error)
	SaveConfig(context.Context, *SaveConfig_Request) (*SaveConfig_Response, error)
	GetConfig(context.Context, *GetConfig_Request) (*GetConfig_Response, error)
	GetConfigNodes(context.Context, *GetConfigNode_Request) (*GetConfigNode_Response, error)
	PatchConfig(context.Context, *PatchConfig_Request) (*PatchConfig_Response, error)
	RenameConfig(context.Context, *RenameConfig_Request) (*RenameConfig_Response, error)
	DeleteConfig(context.Context, *DeleteConfig_Request) (*DeleteConfig_Response, error)
	SubscribeOnChanges(grpc.BidiStreamingServer[SubscribeOnChanges_Request, SubscribeOnChanges_Response]) error
	mustEmbedUnimplementedMatreshkaApiServer()
}

// UnimplementedMatreshkaApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatreshkaApiServer struct{}

func (UnimplementedMatreshkaApiServer) Version(context.Context, *Version_Request) (*Version_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedMatreshkaApiServer) ListConfigs(context.Context, *ListConfigs_Request) (*ListConfigs_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedMatreshkaApiServer) CreateConfig(context.Context, *CreateConfig_Request) (*CreateConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConfig not implemented")
}
func (UnimplementedMatreshkaApiServer) SaveConfig(context.Context, *SaveConfig_Request) (*SaveConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedMatreshkaApiServer) GetConfig(context.Context, *GetConfig_Request) (*GetConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedMatreshkaApiServer) GetConfigNodes(context.Context, *GetConfigNode_Request) (*GetConfigNode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigNodes not implemented")
}
func (UnimplementedMatreshkaApiServer) PatchConfig(context.Context, *PatchConfig_Request) (*PatchConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchConfig not implemented")
}
func (UnimplementedMatreshkaApiServer) RenameConfig(context.Context, *RenameConfig_Request) (*RenameConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameConfig not implemented")
}
func (UnimplementedMatreshkaApiServer) DeleteConfig(context.Context, *DeleteConfig_Request) (*DeleteConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedMatreshkaApiServer) SubscribeOnChanges(grpc.BidiStreamingServer[SubscribeOnChanges_Request, SubscribeOnChanges_Response]) error {
	return status.Error(codes.Unimplemented, "method SubscribeOnChanges not implemented")
}
func (UnimplementedMatreshkaApiServer) mustEmbedUnimplementedMatreshkaApiServer() {}
func (UnimplementedMatreshkaApiServer) testEmbeddedByValue()                      {}

// UnsafeMatreshkaApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatreshkaApiServer will
// result in compilation errors.
type UnsafeMatreshkaApiServer interface {
	mustEmbedUnimplementedMatreshkaApiServer()
}

func RegisterMatreshkaApiServer(s grpc.ServiceRegistrar, srv MatreshkaApiServer) {
	// If the following call panics, it indicates UnimplementedMatreshkaApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatreshkaApi_ServiceDesc, srv)
}

func _MatreshkaApi_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Version_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).Version(ctx, req.(*Version_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigs_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_ListConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).ListConfigs(ctx, req.(*ListConfigs_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_CreateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).CreateConfig(ctx, req.(*CreateConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).SaveConfig(ctx, req.(*SaveConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).GetConfig(ctx, req.(*GetConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_GetConfigNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigNode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).GetConfigNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_GetConfigNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).GetConfigNodes(ctx, req.(*GetConfigNode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_PatchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).PatchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_PatchConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).PatchConfig(ctx, req.(*PatchConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_RenameConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).RenameConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_RenameConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).RenameConfig(ctx, req.(*RenameConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatreshkaApiServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatreshkaApi_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatreshkaApiServer).DeleteConfig(ctx, req.(*DeleteConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatreshkaApi_SubscribeOnChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MatreshkaApiServer).SubscribeOnChanges(&grpc.GenericServerStream[SubscribeOnChanges_Request, SubscribeOnChanges_Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatreshkaApi_SubscribeOnChangesServer = grpc.BidiStreamingServer[SubscribeOnChanges_Request, SubscribeOnChanges_Response]

// MatreshkaApi_ServiceDesc is the grpc.ServiceDesc for MatreshkaApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatreshkaApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matreshka_api.MatreshkaApi",
	HandlerType: (*MatreshkaApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _MatreshkaApi_Version_Handler,
		},
		{
			MethodName: "ListConfigs",
			Handler:    _MatreshkaApi_ListConfigs_Handler,
		},
		{
			MethodName: "CreateConfig",
			Handler:    _MatreshkaApi_CreateConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _MatreshkaApi_SaveConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _MatreshkaApi_GetConfig_Handler,
		},
		{
			MethodName: "GetConfigNodes",
			Handler:    _MatreshkaApi_GetConfigNodes_Handler,
		},
		{
			MethodName: "PatchConfig",
			Handler:    _MatreshkaApi_PatchConfig_Handler,
		},
		{
			MethodName: "RenameConfig",
			Handler:    _MatreshkaApi_RenameConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _MatreshkaApi_DeleteConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOnChanges",
			Handler:       _MatreshkaApi_SubscribeOnChanges_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "matreshka_api.proto",
}
