// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: matreshka_api.proto

package matreshka_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_matreshka_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{0}
}

type ListConfigs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigs) Reset() {
	*x = ListConfigs{}
	mi := &file_matreshka_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigs) ProtoMessage() {}

func (x *ListConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigs.ProtoReflect.Descriptor instead.
func (*ListConfigs) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{1}
}

type CreateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfig) Reset() {
	*x = CreateConfig{}
	mi := &file_matreshka_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfig) ProtoMessage() {}

func (x *CreateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfig.ProtoReflect.Descriptor instead.
func (*CreateConfig) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{2}
}

type GetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfig) Reset() {
	*x = GetConfig{}
	mi := &file_matreshka_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfig) ProtoMessage() {}

func (x *GetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfig.ProtoReflect.Descriptor instead.
func (*GetConfig) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{3}
}

type PatchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchConfig) Reset() {
	*x = PatchConfig{}
	mi := &file_matreshka_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConfig) ProtoMessage() {}

func (x *PatchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConfig.ProtoReflect.Descriptor instead.
func (*PatchConfig) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{4}
}

type SaveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfig) Reset() {
	*x = SaveConfig{}
	mi := &file_matreshka_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfig) ProtoMessage() {}

func (x *SaveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfig.ProtoReflect.Descriptor instead.
func (*SaveConfig) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{5}
}

type GetConfigNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigNode) Reset() {
	*x = GetConfigNode{}
	mi := &file_matreshka_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigNode) ProtoMessage() {}

func (x *GetConfigNode) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigNode.ProtoReflect.Descriptor instead.
func (*GetConfigNode) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{6}
}

type RenameConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameConfig) Reset() {
	*x = RenameConfig{}
	mi := &file_matreshka_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameConfig) ProtoMessage() {}

func (x *RenameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameConfig.ProtoReflect.Descriptor instead.
func (*RenameConfig) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{7}
}

type SubscribeOnChanges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOnChanges) Reset() {
	*x = SubscribeOnChanges{}
	mi := &file_matreshka_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOnChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOnChanges) ProtoMessage() {}

func (x *SubscribeOnChanges) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOnChanges.ProtoReflect.Descriptor instead.
func (*SubscribeOnChanges) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{8}
}

type DeleteConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfig) Reset() {
	*x = DeleteConfig{}
	mi := &file_matreshka_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfig) ProtoMessage() {}

func (x *DeleteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfig.ProtoReflect.Descriptor instead.
func (*DeleteConfig) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{9}
}

type Version_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version_Request) Reset() {
	*x = Version_Request{}
	mi := &file_matreshka_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Request) ProtoMessage() {}

func (x *Version_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Request.ProtoReflect.Descriptor instead.
func (*Version_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{0, 0}
}

type Version_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version_Response) Reset() {
	*x = Version_Response{}
	mi := &file_matreshka_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Response) ProtoMessage() {}

func (x *Version_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Response.ProtoReflect.Descriptor instead.
func (*Version_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Version_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListConfigs_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *Paging                `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Sort          *Sort                  `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	SearchPattern *string                `protobuf:"bytes,3,opt,name=search_pattern,json=searchPattern,proto3,oneof" json:"search_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigs_Request) Reset() {
	*x = ListConfigs_Request{}
	mi := &file_matreshka_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigs_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigs_Request) ProtoMessage() {}

func (x *ListConfigs_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigs_Request.ProtoReflect.Descriptor instead.
func (*ListConfigs_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListConfigs_Request) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListConfigs_Request) GetSort() *Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListConfigs_Request) GetSearchPattern() string {
	if x != nil && x.SearchPattern != nil {
		return *x.SearchPattern
	}
	return ""
}

type ListConfigs_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ConfigBase          `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	TotalRecords  uint64                 `protobuf:"varint,2,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigs_Response) Reset() {
	*x = ListConfigs_Response{}
	mi := &file_matreshka_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigs_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigs_Response) ProtoMessage() {}

func (x *ListConfigs_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigs_Response.ProtoReflect.Descriptor instead.
func (*ListConfigs_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListConfigs_Response) GetConfigs() []*ConfigBase {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListConfigs_Response) GetTotalRecords() uint64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type CreateConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigType    ConfigType             `protobuf:"varint,2,opt,name=config_type,json=configType,proto3,enum=matreshka_api.ConfigType" json:"config_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfig_Request) Reset() {
	*x = CreateConfig_Request{}
	mi := &file_matreshka_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfig_Request) ProtoMessage() {}

func (x *CreateConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfig_Request.ProtoReflect.Descriptor instead.
func (*CreateConfig_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateConfig_Request) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *CreateConfig_Request) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_plain
}

type CreateConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfig_Response) Reset() {
	*x = CreateConfig_Response{}
	mi := &file_matreshka_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfig_Response) ProtoMessage() {}

func (x *CreateConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfig_Response.ProtoReflect.Descriptor instead.
func (*CreateConfig_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{2, 1}
}

type GetConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Version       *string                `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Format        Format                 `protobuf:"varint,3,opt,name=format,proto3,enum=matreshka_api.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfig_Request) Reset() {
	*x = GetConfig_Request{}
	mi := &file_matreshka_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfig_Request) ProtoMessage() {}

func (x *GetConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfig_Request.ProtoReflect.Descriptor instead.
func (*GetConfig_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetConfig_Request) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *GetConfig_Request) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *GetConfig_Request) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_yaml
}

type GetConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Info          *ConfigInfo            `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfig_Response) Reset() {
	*x = GetConfig_Response{}
	mi := &file_matreshka_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfig_Response) ProtoMessage() {}

func (x *GetConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfig_Response.ProtoReflect.Descriptor instead.
func (*GetConfig_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetConfig_Response) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfig_Response) GetInfo() *ConfigInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PatchConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Version       *string                `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Patches       []*Patch               `protobuf:"bytes,3,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchConfig_Request) Reset() {
	*x = PatchConfig_Request{}
	mi := &file_matreshka_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConfig_Request) ProtoMessage() {}

func (x *PatchConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConfig_Request.ProtoReflect.Descriptor instead.
func (*PatchConfig_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PatchConfig_Request) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *PatchConfig_Request) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *PatchConfig_Request) GetPatches() []*Patch {
	if x != nil {
		return x.Patches
	}
	return nil
}

type PatchConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchConfig_Response) Reset() {
	*x = PatchConfig_Response{}
	mi := &file_matreshka_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConfig_Response) ProtoMessage() {}

func (x *PatchConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConfig_Response.ProtoReflect.Descriptor instead.
func (*PatchConfig_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{4, 1}
}

type SaveConfig_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config format. Default - yaml
	Format        Format  `protobuf:"varint,1,opt,name=format,proto3,enum=matreshka_api.Format" json:"format,omitempty"`
	ConfigName    string  `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Version       *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Config        []byte  `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfig_Request) Reset() {
	*x = SaveConfig_Request{}
	mi := &file_matreshka_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfig_Request) ProtoMessage() {}

func (x *SaveConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfig_Request.ProtoReflect.Descriptor instead.
func (*SaveConfig_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SaveConfig_Request) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_yaml
}

func (x *SaveConfig_Request) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *SaveConfig_Request) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *SaveConfig_Request) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type SaveConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfig_Response) Reset() {
	*x = SaveConfig_Response{}
	mi := &file_matreshka_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfig_Response) ProtoMessage() {}

func (x *SaveConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfig_Response.ProtoReflect.Descriptor instead.
func (*SaveConfig_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{5, 1}
}

type GetConfigNode_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigNode_Request) Reset() {
	*x = GetConfigNode_Request{}
	mi := &file_matreshka_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigNode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigNode_Request) ProtoMessage() {}

func (x *GetConfigNode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigNode_Request.ProtoReflect.Descriptor instead.
func (*GetConfigNode_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetConfigNode_Request) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *GetConfigNode_Request) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetConfigNode_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *Node                  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Versions      []string               `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigNode_Response) Reset() {
	*x = GetConfigNode_Response{}
	mi := &file_matreshka_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigNode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigNode_Response) ProtoMessage() {}

func (x *GetConfigNode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigNode_Response.ProtoReflect.Descriptor instead.
func (*GetConfigNode_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetConfigNode_Response) GetRoot() *Node {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *GetConfigNode_Response) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type RenameConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameConfig_Request) Reset() {
	*x = RenameConfig_Request{}
	mi := &file_matreshka_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameConfig_Request) ProtoMessage() {}

func (x *RenameConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameConfig_Request.ProtoReflect.Descriptor instead.
func (*RenameConfig_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RenameConfig_Request) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *RenameConfig_Request) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewName       string                 `protobuf:"bytes,1,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameConfig_Response) Reset() {
	*x = RenameConfig_Response{}
	mi := &file_matreshka_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameConfig_Response) ProtoMessage() {}

func (x *RenameConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameConfig_Response.ProtoReflect.Descriptor instead.
func (*RenameConfig_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{7, 1}
}

func (x *RenameConfig_Response) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type SubscribeOnChanges_Request struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SubscribeConfigNames   []string               `protobuf:"bytes,1,rep,name=subscribe_config_names,json=subscribeConfigNames,proto3" json:"subscribe_config_names,omitempty"`
	UnsubscribeConfigNames []string               `protobuf:"bytes,2,rep,name=unsubscribe_config_names,json=unsubscribeConfigNames,proto3" json:"unsubscribe_config_names,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SubscribeOnChanges_Request) Reset() {
	*x = SubscribeOnChanges_Request{}
	mi := &file_matreshka_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOnChanges_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOnChanges_Request) ProtoMessage() {}

func (x *SubscribeOnChanges_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOnChanges_Request.ProtoReflect.Descriptor instead.
func (*SubscribeOnChanges_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{8, 0}
}

func (x *SubscribeOnChanges_Request) GetSubscribeConfigNames() []string {
	if x != nil {
		return x.SubscribeConfigNames
	}
	return nil
}

func (x *SubscribeOnChanges_Request) GetUnsubscribeConfigNames() []string {
	if x != nil {
		return x.UnsubscribeConfigNames
	}
	return nil
}

type SubscribeOnChanges_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Timestamp     uint32                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Patches       []*Patch               `protobuf:"bytes,3,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOnChanges_Response) Reset() {
	*x = SubscribeOnChanges_Response{}
	mi := &file_matreshka_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOnChanges_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOnChanges_Response) ProtoMessage() {}

func (x *SubscribeOnChanges_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOnChanges_Response.ProtoReflect.Descriptor instead.
func (*SubscribeOnChanges_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{8, 1}
}

func (x *SubscribeOnChanges_Response) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *SubscribeOnChanges_Response) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SubscribeOnChanges_Response) GetPatches() []*Patch {
	if x != nil {
		return x.Patches
	}
	return nil
}

type DeleteConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigVersion *string                `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3,oneof" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfig_Request) Reset() {
	*x = DeleteConfig_Request{}
	mi := &file_matreshka_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfig_Request) ProtoMessage() {}

func (x *DeleteConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfig_Request.ProtoReflect.Descriptor instead.
func (*DeleteConfig_Request) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{9, 0}
}

func (x *DeleteConfig_Request) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *DeleteConfig_Request) GetConfigVersion() string {
	if x != nil && x.ConfigVersion != nil {
		return *x.ConfigVersion
	}
	return ""
}

type DeleteConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfig_Response) Reset() {
	*x = DeleteConfig_Response{}
	mi := &file_matreshka_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfig_Response) ProtoMessage() {}

func (x *DeleteConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfig_Response.ProtoReflect.Descriptor instead.
func (*DeleteConfig_Response) Descriptor() ([]byte, []int) {
	return file_matreshka_api_proto_rawDescGZIP(), []int{9, 1}
}

var File_matreshka_api_proto protoreflect.FileDescriptor

const file_matreshka_api_proto_rawDesc = "" +
	"\n" +
	"\x13matreshka_api.proto\x12\rmatreshka_api\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\x1a\x16matreshka_common.proto\":\n" +
	"\aVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x96\x02\n" +
	"\vListConfigs\x1a\xa0\x01\n" +
	"\aRequest\x12-\n" +
	"\x06paging\x18\x01 \x01(\v2\x15.matreshka_api.PagingR\x06paging\x12'\n" +
	"\x04sort\x18\x02 \x01(\v2\x13.matreshka_api.SortR\x04sort\x12*\n" +
	"\x0esearch_pattern\x18\x03 \x01(\tH\x00R\rsearchPattern\x88\x01\x01B\x11\n" +
	"\x0f_search_pattern\x1ad\n" +
	"\bResponse\x123\n" +
	"\aconfigs\x18\x01 \x03(\v2\x19.matreshka_api.ConfigBaseR\aconfigs\x12#\n" +
	"\rtotal_records\x18\x02 \x01(\x04R\ftotalRecords\"\x82\x01\n" +
	"\fCreateConfig\x1af\n" +
	"\aRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12:\n" +
	"\vconfig_type\x18\x02 \x01(\x0e2\x19.matreshka_api.ConfigTypeR\n" +
	"configType\x1a\n" +
	"\n" +
	"\bResponse\"\xe5\x01\n" +
	"\tGetConfig\x1a\x84\x01\n" +
	"\aRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tH\x00R\aversion\x88\x01\x01\x12-\n" +
	"\x06format\x18\x03 \x01(\x0e2\x15.matreshka_api.FormatR\x06formatB\n" +
	"\n" +
	"\b_version\x1aQ\n" +
	"\bResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12-\n" +
	"\x04info\x18\x02 \x01(\v2\x19.matreshka_api.ConfigInfoR\x04info\"\xa1\x01\n" +
	"\vPatchConfig\x1a\x85\x01\n" +
	"\aRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tH\x00R\aversion\x88\x01\x01\x12.\n" +
	"\apatches\x18\x03 \x03(\v2\x14.matreshka_api.PatchR\apatchesB\n" +
	"\n" +
	"\b_version\x1a\n" +
	"\n" +
	"\bResponse\"\xb7\x01\n" +
	"\n" +
	"SaveConfig\x1a\x9c\x01\n" +
	"\aRequest\x12-\n" +
	"\x06format\x18\x01 \x01(\x0e2\x15.matreshka_api.FormatR\x06format\x12\x1f\n" +
	"\vconfig_name\x18\x02 \x01(\tR\n" +
	"configName\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x00R\aversion\x88\x01\x01\x12\x16\n" +
	"\x06config\x18\x04 \x01(\fR\x06configB\n" +
	"\n" +
	"\b_version\x1a\n" +
	"\n" +
	"\bResponse\"\xa6\x01\n" +
	"\rGetConfigNode\x1aD\n" +
	"\aRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x1aO\n" +
	"\bResponse\x12'\n" +
	"\x04root\x18\x01 \x01(\v2\x13.matreshka_api.NodeR\x04root\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\tR\bversions\"|\n" +
	"\fRenameConfig\x1aE\n" +
	"\aRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\x1a%\n" +
	"\bResponse\x12\x19\n" +
	"\bnew_name\x18\x01 \x01(\tR\anewName\"\x8a\x02\n" +
	"\x12SubscribeOnChanges\x1ay\n" +
	"\aRequest\x124\n" +
	"\x16subscribe_config_names\x18\x01 \x03(\tR\x14subscribeConfigNames\x128\n" +
	"\x18unsubscribe_config_names\x18\x02 \x03(\tR\x16unsubscribeConfigNames\x1ay\n" +
	"\bResponse\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\rR\ttimestamp\x12.\n" +
	"\apatches\x18\x03 \x03(\v2\x14.matreshka_api.PatchR\apatches\"\x85\x01\n" +
	"\fDeleteConfig\x1ai\n" +
	"\aRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12*\n" +
	"\x0econfig_version\x18\x02 \x01(\tH\x00R\rconfigVersion\x88\x01\x01B\x11\n" +
	"\x0f_config_version\x1a\n" +
	"\n" +
	"\bResponse2\xe3\t\n" +
	"\fMatreshkaApi\x12`\n" +
	"\aVersion\x12\x1e.matreshka_api.Version.Request\x1a\x1f.matreshka_api.Version.Response\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/version\x12s\n" +
	"\vListConfigs\x12\".matreshka_api.ListConfigs.Request\x1a#.matreshka_api.ListConfigs.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/config/list\x12x\n" +
	"\fCreateConfig\x12#.matreshka_api.CreateConfig.Request\x1a$.matreshka_api.CreateConfig.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/config/create\x12~\n" +
	"\n" +
	"SaveConfig\x12!.matreshka_api.SaveConfig.Request\x1a\".matreshka_api.SaveConfig.Response\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/config/{config_name}/Save\x12s\n" +
	"\tGetConfig\x12 .matreshka_api.GetConfig.Request\x1a!.matreshka_api.GetConfig.Response\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/config/{config_name}\x12{\n" +
	"\x0eGetConfigNodes\x12$.matreshka_api.GetConfigNode.Request\x1a%.matreshka_api.GetConfigNode.Response\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/config/nodes\x12\x82\x01\n" +
	"\vPatchConfig\x12\".matreshka_api.PatchConfig.Request\x1a#.matreshka_api.PatchConfig.Response\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/config/{config_name}/patch\x12\x8e\x01\n" +
	"\fRenameConfig\x12#.matreshka_api.RenameConfig.Request\x1a$.matreshka_api.RenameConfig.Response\"3\x82\xd3\xe4\x93\x02-\"+/api/config/{config_name}/rename/{new_name}\x12\x86\x01\n" +
	"\fDeleteConfig\x12#.matreshka_api.DeleteConfig.Request\x1a$.matreshka_api.DeleteConfig.Response\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/config/{config_name}/delete\x12q\n" +
	"\x12SubscribeOnChanges\x12).matreshka_api.SubscribeOnChanges.Request\x1a*.matreshka_api.SubscribeOnChanges.Response\"\x00(\x010\x01BS\x92\x82\x19\x14@vervstack/matreshkaZ9go.vervstack.ru/matreshka/pkg/matreshka_api;matreshka_apib\x06proto3"

var (
	file_matreshka_api_proto_rawDescOnce sync.Once
	file_matreshka_api_proto_rawDescData []byte
)

func file_matreshka_api_proto_rawDescGZIP() []byte {
	file_matreshka_api_proto_rawDescOnce.Do(func() {
		file_matreshka_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matreshka_api_proto_rawDesc), len(file_matreshka_api_proto_rawDesc)))
	})
	return file_matreshka_api_proto_rawDescData
}

var file_matreshka_api_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_matreshka_api_proto_goTypes = []any{
	(*Version)(nil),                     // 0: matreshka_api.Version
	(*ListConfigs)(nil),                 // 1: matreshka_api.ListConfigs
	(*CreateConfig)(nil),                // 2: matreshka_api.CreateConfig
	(*GetConfig)(nil),                   // 3: matreshka_api.GetConfig
	(*PatchConfig)(nil),                 // 4: matreshka_api.PatchConfig
	(*SaveConfig)(nil),                  // 5: matreshka_api.SaveConfig
	(*GetConfigNode)(nil),               // 6: matreshka_api.GetConfigNode
	(*RenameConfig)(nil),                // 7: matreshka_api.RenameConfig
	(*SubscribeOnChanges)(nil),          // 8: matreshka_api.SubscribeOnChanges
	(*DeleteConfig)(nil),                // 9: matreshka_api.DeleteConfig
	(*Version_Request)(nil),             // 10: matreshka_api.Version.Request
	(*Version_Response)(nil),            // 11: matreshka_api.Version.Response
	(*ListConfigs_Request)(nil),         // 12: matreshka_api.ListConfigs.Request
	(*ListConfigs_Response)(nil),        // 13: matreshka_api.ListConfigs.Response
	(*CreateConfig_Request)(nil),        // 14: matreshka_api.CreateConfig.Request
	(*CreateConfig_Response)(nil),       // 15: matreshka_api.CreateConfig.Response
	(*GetConfig_Request)(nil),           // 16: matreshka_api.GetConfig.Request
	(*GetConfig_Response)(nil),          // 17: matreshka_api.GetConfig.Response
	(*PatchConfig_Request)(nil),         // 18: matreshka_api.PatchConfig.Request
	(*PatchConfig_Response)(nil),        // 19: matreshka_api.PatchConfig.Response
	(*SaveConfig_Request)(nil),          // 20: matreshka_api.SaveConfig.Request
	(*SaveConfig_Response)(nil),         // 21: matreshka_api.SaveConfig.Response
	(*GetConfigNode_Request)(nil),       // 22: matreshka_api.GetConfigNode.Request
	(*GetConfigNode_Response)(nil),      // 23: matreshka_api.GetConfigNode.Response
	(*RenameConfig_Request)(nil),        // 24: matreshka_api.RenameConfig.Request
	(*RenameConfig_Response)(nil),       // 25: matreshka_api.RenameConfig.Response
	(*SubscribeOnChanges_Request)(nil),  // 26: matreshka_api.SubscribeOnChanges.Request
	(*SubscribeOnChanges_Response)(nil), // 27: matreshka_api.SubscribeOnChanges.Response
	(*DeleteConfig_Request)(nil),        // 28: matreshka_api.DeleteConfig.Request
	(*DeleteConfig_Response)(nil),       // 29: matreshka_api.DeleteConfig.Response
	(*Paging)(nil),                      // 30: matreshka_api.Paging
	(*Sort)(nil),                        // 31: matreshka_api.Sort
	(*ConfigBase)(nil),                  // 32: matreshka_api.ConfigBase
	(ConfigType)(0),                     // 33: matreshka_api.ConfigType
	(Format)(0),                         // 34: matreshka_api.Format
	(*ConfigInfo)(nil),                  // 35: matreshka_api.ConfigInfo
	(*Patch)(nil),                       // 36: matreshka_api.Patch
	(*Node)(nil),                        // 37: matreshka_api.Node
}
var file_matreshka_api_proto_depIdxs = []int32{
	30, // 0: matreshka_api.ListConfigs.Request.paging:type_name -> matreshka_api.Paging
	31, // 1: matreshka_api.ListConfigs.Request.sort:type_name -> matreshka_api.Sort
	32, // 2: matreshka_api.ListConfigs.Response.configs:type_name -> matreshka_api.ConfigBase
	33, // 3: matreshka_api.CreateConfig.Request.config_type:type_name -> matreshka_api.ConfigType
	34, // 4: matreshka_api.GetConfig.Request.format:type_name -> matreshka_api.Format
	35, // 5: matreshka_api.GetConfig.Response.info:type_name -> matreshka_api.ConfigInfo
	36, // 6: matreshka_api.PatchConfig.Request.patches:type_name -> matreshka_api.Patch
	34, // 7: matreshka_api.SaveConfig.Request.format:type_name -> matreshka_api.Format
	37, // 8: matreshka_api.GetConfigNode.Response.root:type_name -> matreshka_api.Node
	36, // 9: matreshka_api.SubscribeOnChanges.Response.patches:type_name -> matreshka_api.Patch
	10, // 10: matreshka_api.MatreshkaApi.Version:input_type -> matreshka_api.Version.Request
	12, // 11: matreshka_api.MatreshkaApi.ListConfigs:input_type -> matreshka_api.ListConfigs.Request
	14, // 12: matreshka_api.MatreshkaApi.CreateConfig:input_type -> matreshka_api.CreateConfig.Request
	20, // 13: matreshka_api.MatreshkaApi.SaveConfig:input_type -> matreshka_api.SaveConfig.Request
	16, // 14: matreshka_api.MatreshkaApi.GetConfig:input_type -> matreshka_api.GetConfig.Request
	22, // 15: matreshka_api.MatreshkaApi.GetConfigNodes:input_type -> matreshka_api.GetConfigNode.Request
	18, // 16: matreshka_api.MatreshkaApi.PatchConfig:input_type -> matreshka_api.PatchConfig.Request
	24, // 17: matreshka_api.MatreshkaApi.RenameConfig:input_type -> matreshka_api.RenameConfig.Request
	28, // 18: matreshka_api.MatreshkaApi.DeleteConfig:input_type -> matreshka_api.DeleteConfig.Request
	26, // 19: matreshka_api.MatreshkaApi.SubscribeOnChanges:input_type -> matreshka_api.SubscribeOnChanges.Request
	11, // 20: matreshka_api.MatreshkaApi.Version:output_type -> matreshka_api.Version.Response
	13, // 21: matreshka_api.MatreshkaApi.ListConfigs:output_type -> matreshka_api.ListConfigs.Response
	15, // 22: matreshka_api.MatreshkaApi.CreateConfig:output_type -> matreshka_api.CreateConfig.Response
	21, // 23: matreshka_api.MatreshkaApi.SaveConfig:output_type -> matreshka_api.SaveConfig.Response
	17, // 24: matreshka_api.MatreshkaApi.GetConfig:output_type -> matreshka_api.GetConfig.Response
	23, // 25: matreshka_api.MatreshkaApi.GetConfigNodes:output_type -> matreshka_api.GetConfigNode.Response
	19, // 26: matreshka_api.MatreshkaApi.PatchConfig:output_type -> matreshka_api.PatchConfig.Response
	25, // 27: matreshka_api.MatreshkaApi.RenameConfig:output_type -> matreshka_api.RenameConfig.Response
	29, // 28: matreshka_api.MatreshkaApi.DeleteConfig:output_type -> matreshka_api.DeleteConfig.Response
	27, // 29: matreshka_api.MatreshkaApi.SubscribeOnChanges:output_type -> matreshka_api.SubscribeOnChanges.Response
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_matreshka_api_proto_init() }
func file_matreshka_api_proto_init() {
	if File_matreshka_api_proto != nil {
		return
	}
	file_matreshka_common_proto_init()
	file_matreshka_api_proto_msgTypes[12].OneofWrappers = []any{}
	file_matreshka_api_proto_msgTypes[16].OneofWrappers = []any{}
	file_matreshka_api_proto_msgTypes[18].OneofWrappers = []any{}
	file_matreshka_api_proto_msgTypes[20].OneofWrappers = []any{}
	file_matreshka_api_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matreshka_api_proto_rawDesc), len(file_matreshka_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matreshka_api_proto_goTypes,
		DependencyIndexes: file_matreshka_api_proto_depIdxs,
		MessageInfos:      file_matreshka_api_proto_msgTypes,
	}.Build()
	File_matreshka_api_proto = out.File
	file_matreshka_api_proto_goTypes = nil
	file_matreshka_api_proto_depIdxs = nil
}
