// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: matreshka_common.proto

package matreshka_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigType int32

const (
	// Plain text blob config - saved and configured externally by user
	// Not recommended to use - unstructured and cannot be validated.
	// Simply a text storage
	ConfigType_plain ConfigType = 0
	// Matreshka's configuration for application
	ConfigType_verv ConfigType = 1
	// Configuration for object storage (Minio)
	ConfigType_minio ConfigType = 2
	// Configuration for Postgresql Database
	ConfigType_pg ConfigType = 3
	// Configuration for Nginx/Angie web server
	ConfigType_nginx ConfigType = 4
	// Basically a key-value configuration
	ConfigType_kv ConfigType = 5
)

// Enum value maps for ConfigType.
var (
	ConfigType_name = map[int32]string{
		0: "plain",
		1: "verv",
		2: "minio",
		3: "pg",
		4: "nginx",
		5: "kv",
	}
	ConfigType_value = map[string]int32{
		"plain": 0,
		"verv":  1,
		"minio": 2,
		"pg":    3,
		"nginx": 4,
		"kv":    5,
	}
)

func (x ConfigType) Enum() *ConfigType {
	p := new(ConfigType)
	*p = x
	return p
}

func (x ConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_matreshka_common_proto_enumTypes[0].Descriptor()
}

func (ConfigType) Type() protoreflect.EnumType {
	return &file_matreshka_common_proto_enumTypes[0]
}

func (x ConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigType.Descriptor instead.
func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{0}
}

type Format int32

const (
	Format_yaml Format = 0 // Default
	Format_env  Format = 1
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "yaml",
		1: "env",
	}
	Format_value = map[string]int32{
		"yaml": 0,
		"env":  1,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_matreshka_common_proto_enumTypes[1].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_matreshka_common_proto_enumTypes[1]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{1}
}

type Sort_Type int32

const (
	Sort_default       Sort_Type = 0
	Sort_by_name       Sort_Type = 1
	Sort_by_updated_at Sort_Type = 2
)

// Enum value maps for Sort_Type.
var (
	Sort_Type_name = map[int32]string{
		0: "default",
		1: "by_name",
		2: "by_updated_at",
	}
	Sort_Type_value = map[string]int32{
		"default":       0,
		"by_name":       1,
		"by_updated_at": 2,
	}
)

func (x Sort_Type) Enum() *Sort_Type {
	p := new(Sort_Type)
	*p = x
	return p
}

func (x Sort_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_matreshka_common_proto_enumTypes[2].Descriptor()
}

func (Sort_Type) Type() protoreflect.EnumType {
	return &file_matreshka_common_proto_enumTypes[2]
}

func (x Sort_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort_Type.Descriptor instead.
func (Sort_Type) EnumDescriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{1, 0}
}

type Paging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paging) Reset() {
	*x = Paging{}
	mi := &file_matreshka_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{0}
}

func (x *Paging) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Paging) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Sort_Type              `protobuf:"varint,1,opt,name=type,proto3,enum=matreshka_api.Sort_Type" json:"type,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_matreshka_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{1}
}

func (x *Sort) GetType() Sort_Type {
	if x != nil {
		return x.Type
	}
	return Sort_default
}

func (x *Sort) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	InnerNodes    []*Node                `protobuf:"bytes,3,rep,name=inner_nodes,json=innerNodes,proto3" json:"inner_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_matreshka_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *Node) GetInnerNodes() []*Node {
	if x != nil {
		return x.InnerNodes
	}
	return nil
}

type ConfigBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ConfigType    ConfigType             `protobuf:"varint,5,opt,name=config_type,json=configType,proto3,enum=matreshka_api.ConfigType" json:"config_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigBase) Reset() {
	*x = ConfigBase{}
	mi := &file_matreshka_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigBase) ProtoMessage() {}

func (x *ConfigBase) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigBase.ProtoReflect.Descriptor instead.
func (*ConfigBase) Descriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigBase) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigBase) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigBase) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfigBase) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_plain
}

type ConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigBase    *ConfigBase            `protobuf:"bytes,1,opt,name=config_base,json=configBase,proto3" json:"config_base,omitempty"`
	Versions      []string               `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_matreshka_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigInfo) GetConfigBase() *ConfigBase {
	if x != nil {
		return x.ConfigBase
	}
	return nil
}

func (x *ConfigInfo) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type Patch struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FieldName string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Types that are valid to be assigned to Patch:
	//
	//	*Patch_Rename
	//	*Patch_UpdateValue
	//	*Patch_Delete
	Patch         isPatch_Patch `protobuf_oneof:"patch"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patch) Reset() {
	*x = Patch{}
	mi := &file_matreshka_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patch) ProtoMessage() {}

func (x *Patch) ProtoReflect() protoreflect.Message {
	mi := &file_matreshka_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patch.ProtoReflect.Descriptor instead.
func (*Patch) Descriptor() ([]byte, []int) {
	return file_matreshka_common_proto_rawDescGZIP(), []int{5}
}

func (x *Patch) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *Patch) GetPatch() isPatch_Patch {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *Patch) GetRename() string {
	if x != nil {
		if x, ok := x.Patch.(*Patch_Rename); ok {
			return x.Rename
		}
	}
	return ""
}

func (x *Patch) GetUpdateValue() string {
	if x != nil {
		if x, ok := x.Patch.(*Patch_UpdateValue); ok {
			return x.UpdateValue
		}
	}
	return ""
}

func (x *Patch) GetDelete() bool {
	if x != nil {
		if x, ok := x.Patch.(*Patch_Delete); ok {
			return x.Delete
		}
	}
	return false
}

type isPatch_Patch interface {
	isPatch_Patch()
}

type Patch_Rename struct {
	Rename string `protobuf:"bytes,2,opt,name=rename,proto3,oneof"`
}

type Patch_UpdateValue struct {
	UpdateValue string `protobuf:"bytes,3,opt,name=update_value,json=updateValue,proto3,oneof"`
}

type Patch_Delete struct {
	Delete bool `protobuf:"varint,4,opt,name=delete,proto3,oneof"`
}

func (*Patch_Rename) isPatch_Patch() {}

func (*Patch_UpdateValue) isPatch_Patch() {}

func (*Patch_Delete) isPatch_Patch() {}

var File_matreshka_common_proto protoreflect.FileDescriptor

const file_matreshka_common_proto_rawDesc = "" +
	"\n" +
	"\x16matreshka_common.proto\x12\rmatreshka_api\x1a\tnpm.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\x06Paging\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"}\n" +
	"\x04Sort\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.matreshka_api.Sort.TypeR\x04type\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"3\n" +
	"\x04Type\x12\v\n" +
	"\adefault\x10\x00\x12\v\n" +
	"\aby_name\x10\x01\x12\x11\n" +
	"\rby_updated_at\x10\x02\"u\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01\x124\n" +
	"\vinner_nodes\x18\x03 \x03(\v2\x13.matreshka_api.NodeR\n" +
	"innerNodesB\b\n" +
	"\x06_value\"\xe2\x01\n" +
	"\n" +
	"ConfigBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12:\n" +
	"\vconfig_type\x18\x05 \x01(\x0e2\x19.matreshka_api.ConfigTypeR\n" +
	"configType\"d\n" +
	"\n" +
	"ConfigInfo\x12:\n" +
	"\vconfig_base\x18\x01 \x01(\v2\x19.matreshka_api.ConfigBaseR\n" +
	"configBase\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\tR\bversions\"\x88\x01\n" +
	"\x05Patch\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x18\n" +
	"\x06rename\x18\x02 \x01(\tH\x00R\x06rename\x12#\n" +
	"\fupdate_value\x18\x03 \x01(\tH\x00R\vupdateValue\x12\x18\n" +
	"\x06delete\x18\x04 \x01(\bH\x00R\x06deleteB\a\n" +
	"\x05patch*G\n" +
	"\n" +
	"ConfigType\x12\t\n" +
	"\x05plain\x10\x00\x12\b\n" +
	"\x04verv\x10\x01\x12\t\n" +
	"\x05minio\x10\x02\x12\x06\n" +
	"\x02pg\x10\x03\x12\t\n" +
	"\x05nginx\x10\x04\x12\x06\n" +
	"\x02kv\x10\x05*\x1b\n" +
	"\x06Format\x12\b\n" +
	"\x04yaml\x10\x00\x12\a\n" +
	"\x03env\x10\x01BS\x92\x82\x19\x14@vervstack/matreshkaZ9go.vervstack.ru/matreshka/pkg/matreshka_api;matreshka_apib\x06proto3"

var (
	file_matreshka_common_proto_rawDescOnce sync.Once
	file_matreshka_common_proto_rawDescData []byte
)

func file_matreshka_common_proto_rawDescGZIP() []byte {
	file_matreshka_common_proto_rawDescOnce.Do(func() {
		file_matreshka_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matreshka_common_proto_rawDesc), len(file_matreshka_common_proto_rawDesc)))
	})
	return file_matreshka_common_proto_rawDescData
}

var file_matreshka_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_matreshka_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_matreshka_common_proto_goTypes = []any{
	(ConfigType)(0),               // 0: matreshka_api.ConfigType
	(Format)(0),                   // 1: matreshka_api.Format
	(Sort_Type)(0),                // 2: matreshka_api.Sort.Type
	(*Paging)(nil),                // 3: matreshka_api.Paging
	(*Sort)(nil),                  // 4: matreshka_api.Sort
	(*Node)(nil),                  // 5: matreshka_api.Node
	(*ConfigBase)(nil),            // 6: matreshka_api.ConfigBase
	(*ConfigInfo)(nil),            // 7: matreshka_api.ConfigInfo
	(*Patch)(nil),                 // 8: matreshka_api.Patch
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_matreshka_common_proto_depIdxs = []int32{
	2, // 0: matreshka_api.Sort.type:type_name -> matreshka_api.Sort.Type
	5, // 1: matreshka_api.Node.inner_nodes:type_name -> matreshka_api.Node
	9, // 2: matreshka_api.ConfigBase.created_at:type_name -> google.protobuf.Timestamp
	9, // 3: matreshka_api.ConfigBase.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: matreshka_api.ConfigBase.config_type:type_name -> matreshka_api.ConfigType
	6, // 5: matreshka_api.ConfigInfo.config_base:type_name -> matreshka_api.ConfigBase
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_matreshka_common_proto_init() }
func file_matreshka_common_proto_init() {
	if File_matreshka_common_proto != nil {
		return
	}
	file_matreshka_common_proto_msgTypes[2].OneofWrappers = []any{}
	file_matreshka_common_proto_msgTypes[5].OneofWrappers = []any{
		(*Patch_Rename)(nil),
		(*Patch_UpdateValue)(nil),
		(*Patch_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matreshka_common_proto_rawDesc), len(file_matreshka_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matreshka_common_proto_goTypes,
		DependencyIndexes: file_matreshka_common_proto_depIdxs,
		EnumInfos:         file_matreshka_common_proto_enumTypes,
		MessageInfos:      file_matreshka_common_proto_msgTypes,
	}.Build()
	File_matreshka_common_proto = out.File
	file_matreshka_common_proto_goTypes = nil
	file_matreshka_common_proto_depIdxs = nil
}
