// Code generated by RedSock CLI. DO NOT EDIT.

package config

import (
	"flag"

	"go.redsock.ru/rerrors"
	"go.vervstack.ru/matreshka/pkg/matreshka"
)

var ErrAlreadyLoaded = rerrors.New("config already loaded")

type Config struct {
	AppInfo matreshka.AppInfo

	Servers     ServersConfig
	DataSources DataSourcesConfig
	Environment EnvironmentConfig
	Overrides   matreshka.ServiceDiscovery

	MatreshkaConfig matreshka.AppConfig
}

var defaultConfig Config

const (
	devConfigPath  = "./config/dev.yaml"
	prodConfigPath = "./config/config.yaml"
)

func Init() (Config, error) {
	if defaultConfig.AppInfo.Name != "" {
		return defaultConfig, ErrAlreadyLoaded
	}

	var cfgPath string
	var isDevBuild bool

	flag.StringVar(&cfgPath, "config", "", "Path to configuration file")
	flag.BoolVar(&isDevBuild, "dev", false, "Flag turns on a dev config at ./config/dev.yaml")
	flag.Parse()

	var configsPaths []string

	if cfgPath != "" {
		configsPaths = append(configsPaths, cfgPath)
	}

	if isDevBuild {
		configsPaths = append(configsPaths, devConfigPath)
	}
	configsPaths = append(configsPaths, prodConfigPath)

	var err error
	defaultConfig, err = Load(configsPaths...)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error loading config")
	}

	return defaultConfig, nil
}

func Load(configsPaths ...string) (Config, error) {
	var err error
	defaultConfig.MatreshkaConfig, err = matreshka.ReadConfigs(configsPaths...)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error reading matreshka config")
	}

	defaultConfig.AppInfo = defaultConfig.MatreshkaConfig.AppInfo
	defaultConfig.Overrides = defaultConfig.MatreshkaConfig.ServiceDiscovery

	err = defaultConfig.MatreshkaConfig.Servers.
		ParseToStruct(&defaultConfig.Servers)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "Error parsing servers to config")
	}
	err = defaultConfig.MatreshkaConfig.DataSources.
		ParseToStruct(&defaultConfig.DataSources)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error parsing data sources to struct")
	}
	err = defaultConfig.MatreshkaConfig.Environment.
		ParseToStruct(&defaultConfig.Environment)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error parsing environment config")
	}

	return defaultConfig, nil
}
